// <auto-generated />
using System;
using IotRemoteLab.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IotRemoteLab.Persistence.PostgresMigrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240612082547_fix-migr")]
    partial class fixmigr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IotRemoteLab.Domain.Role.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Benchboards.Benchboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benchboard");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Benchboards.BenchboardPort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BenchboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("McuPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RaspberryPiPort")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BenchboardId");

                    b.ToTable("BenchboardPort");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Mcu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssemblyScriptFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeployScriptFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId");

                    b.ToTable("Mcu");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.McuFramework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeFileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("McuFramework");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Stand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BenchboardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeEditorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasBenchboard")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLighting")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSerialPort")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWebcam")
                        .HasColumnType("boolean");

                    b.Property<long>("LightingBrightnessLevel")
                        .HasColumnType("bigint");

                    b.Property<long>("LightingRaspberryPiPort")
                        .HasColumnType("bigint");

                    b.Property<Guid>("McuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<long>("SerialPortSpeed")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebcamUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BenchboardId");

                    b.HasIndex("McuId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Stands");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Uart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Index")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StandId");

                    b.ToTable("Uart");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Team.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Schedule", b =>
                {
                    b.HasOne("IotRemoteLab.Domain.Team.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Benchboards.BenchboardPort", b =>
                {
                    b.HasOne("IotRemoteLab.Domain.Stand.Benchboards.Benchboard", null)
                        .WithMany("Ports")
                        .HasForeignKey("BenchboardId");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Mcu", b =>
                {
                    b.HasOne("IotRemoteLab.Domain.Stand.McuFramework", "Framework")
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Stand", b =>
                {
                    b.HasOne("IotRemoteLab.Domain.Stand.Benchboards.Benchboard", "Benchboard")
                        .WithMany()
                        .HasForeignKey("BenchboardId");

                    b.HasOne("IotRemoteLab.Domain.Stand.Mcu", "Mcu")
                        .WithMany()
                        .HasForeignKey("McuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IotRemoteLab.Domain.Schedule", null)
                        .WithMany("Stands")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Benchboard");

                    b.Navigation("Mcu");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Uart", b =>
                {
                    b.HasOne("IotRemoteLab.Domain.Stand.Stand", null)
                        .WithMany("AvailableUarts")
                        .HasForeignKey("StandId");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.User.User", b =>
                {
                    b.HasOne("IotRemoteLab.Domain.Team.Team", null)
                        .WithMany("Users")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("IotRemoteLab.Domain.Role.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IotRemoteLab.Domain.User.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Schedule", b =>
                {
                    b.Navigation("Stands");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Benchboards.Benchboard", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Stand.Stand", b =>
                {
                    b.Navigation("AvailableUarts");
                });

            modelBuilder.Entity("IotRemoteLab.Domain.Team.Team", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
